### ISSUE TITLE
setOnClickListener is blocked but I need to use it 

### ISSUE THREAD

**Issue by MKevin3** [tiper/MaterialSpinner#19] opened 2019-12-09 17:11 UTC
Due to some code I inherited I need to use setOnClickListener. Basically I want the look and feel of the spinner but when it is clicked on a separate dialog appears. I am not using any of the other features of the spinner, no drop down, etc. but I need the look with the title over the spinner etc. 

I do fully use of your spinner in a number of other areas in the code, this area just happens to be a hackfest.

The code in MaterialSpinner.kt at line 319 blocks this usage - as hacky as it might be.

    override fun setOnClickListener(l: OnClickListener?) {
        throw RuntimeException(
            "Don't call setOnClickListener." +
                    "You probably want setOnItemClickListener instead."
        )
    }

Really need this check to be optional

**Comment by MKevin3** [comment] 2019-12-09 21:03
To get around this issue I put a transparent View on top of the MaterialSpinner and get the onClickListener from there.

**Comment by tiper** [comment] 2019-12-15 01:31
Hi @MKevin3, have you tried setting a `OnFocusChangeListener` instead?

**Comment by tiper** [comment] 2019-12-16 18:12
Possible duplicate of #10

**Comment by tiper** [comment] 2019-12-27 00:42
Hi @MKevin3 any feedback on this?

**Comment by MKevin3** [comment] 2019-12-28 16:29
I just put a view on top of the MaterialSpinner as far as Z-Order is concerned and grab the listener there. While I understand why MaterialSpinner gives the warning in the log as it is a common mistake I don't feel it should be a "and there is NO way you can do this" exception.

**Comment by tiper** [comment] 2019-12-29 14:12
@MKevin3 You should be able to achieve the same functionality without the need of an extra view using the `OnFocusChangeListener`. 

When you click on this view it also gains focus, therefore the focus callback will be triggered, and you will be able to achieve the same effect. Take a look at the sample for a simple example.

**Comment by tiper** [comment] 2020-02-11 12:38
Hi @MKevin3 did you had the time to take a look at tying `OnFocusChangeListener`?

**Closed as completed** 2020-04-16 20:34 UTC
Labels: duplicate
